FROM gradle:jdk17-alpine AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build --no-daemon

FROM openjdk:17.0.1-jdk-slim

ARG SPRING_DOCKER_PORT_1
EXPOSE ${SPRING_DOCKER_PORT_1}

RUN addgroup demogroup; adduser --ingroup demogroup --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --disabled-password app1

RUN mkdir /app
RUN chown app1 /app

USER app1

COPY --from=build /home/gradle/src/build/libs/demo-0.0.1-SNAPSHOT.jar /app/demo.jar

RUN mkdir -p /var/tmp/testfolder
COPY --from=build /home/gradle/src/src/main/resources/testfolder/ /var/tmp/testfolder/

CMD ["java","-jar","-Dserver.port=${SPRING_DOCKER_PORT_1}","/app/demo.jar"]

